version: '3.8'
services:
  devfornet-web:
    build:
      context: ..
      dockerfile: devfornet.Web/Dockerfile
    container_name: devfornet-web
    env_file:
      - ../.env
    ports:
      - "5443:8443" 
      - "5080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - DEVFORNET_URI=${DEVFORNET_URI}
      - API_BASE_URL=http://devfornet-apiservice:80
    networks:
      - devfornet-network

networks:
  devfornet-network:
    external: true
